version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SOLANA_WS_URL=${SOLANA_WS_URL}
      - PUMP_FUN_PROGRAM_ID=${PUMP_FUN_PROGRAM_ID}
      - RATE_LIMIT_RPM=${RATE_LIMIT_RPM}
      - FILTER_SYMBOLS=${FILTER_SYMBOLS}
      - RUST_LOG=${RUST_LOG}
